<a href="https://colab.research.google.com/github/charonux/Colab/blob/master/03_Tensors_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[-1, 2, 3],
              [-4, 5, 6],
              [-7, 8, 9]])

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
c = np.array([1, 2, 3])

print("Sample array & info:")
print(len(a.shape), 'D Tensor,', a.shape[0], 'samples,', a.shape[1], 'features,', \
      a.dtype, 'data type.')

Sample array & info:
2 D Tensor, 3 samples, 3 features, int64 data type.


In [ ]:
def view(x):
    assert len(x.shape) == 2 # only for 2D tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if j < max(range(x.shape[1])):
                print(x[i, j], end=' ')
            else:
                print(x[i, j])

# Element-wise operations
- The relu operation and addition are element-wise operations: operations that are applied independently to each entry in the tensors being considered

In [ ]:
def add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    t = x.copy()

    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            t[i, j] += y[i, j]
    return t
view(a)
print('----------------------')
view(b)
print('----------------------')
view(add(a, b))

-1 2 3
-4 5 6
-7 8 9
----------------------
1 2 3
4 5 6
7 8 9
----------------------
0 4 6
0 10 12
0 16 18


In [ ]:
def relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x
view(a)
print('----------------------')
view(relu(a))

-1 2 3
-4 5 6
-7 8 9
----------------------
0 2 3
0 5 6
0 8 9


- Add and Relu are built-in in Numpy

In [ ]:
print(a + b)

[[ 0  4  6]
 [ 0 10 12]
 [ 0 16 18]]


In [ ]:
print(np.maximum(a, 0.))

[[0. 2. 3.]
 [0. 5. 6.]
 [0. 8. 9.]]


# Sigmoid

In [ ]:
def sigmoid(x, deriv=False):
    if deriv:
        return x*(1 -x)
    return 1/(1+np.exp(-x))
view(a)
print('----------------------')
print(np.round((sigmoid(a)),3))
print('----------------------')
print(np.round((sigmoid(sigmoid(a), deriv=True)), 3))
print(np.round(x,3))

-1 2 3
-4 5 6
-7 8 9
----------------------
[[0.269 0.881 0.953]
 [0.018 0.993 0.998]
 [0.001 1.    1.   ]]
----------------------
[[0.197 0.105 0.045]
 [0.018 0.007 0.002]
 [0.001 0.    0.   ]]
[[0 1 2 3 4 5]]


# Broadcasting
- Addition when the shapes of the two tensors differ:
  The smaller tensor will be broadcasted to match the shape of the larger   tensor. Broadcasting consists of two steps:
- 1 Axes (called broadcast axes) are added to the smaller tensor to match   the ndim of the larger tensor.
- 2 The smaller tensor is repeated alongside these new axes to match the     full shape of the larger tensor.

In [ ]:
def add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x        

In [ ]:
print(a)
print('----------------------')
print(c)
print('----------------------')
print(add_matrix_and_vector(a, c))
print('----------------------')
print(a + c)

[[-1  2  3]
 [-4  5  6]
 [-7  8  9]]
----------------------
[1 2 3]
----------------------
[[ 0  4  6]
 [-3  7  9]
 [-6 10 12]]
----------------------
[[ 0  4  6]
 [-3  7  9]
 [-6 10 12]]


 - Broadcasting is possible for two-tensor element-wise operations if one tensor has shape (a, b, … n, n + 1, … m) and the other has shape (n, n + 1, … m). The broadcasting will then automatically happen for axes a through n - 1.

In [ ]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
print(x.shape)
print(y.shape)
print(z.shape)

(64, 3, 32, 10)
(32, 10)
(64, 3, 32, 10)


In [ ]:
x = np.array([[1, 2, 3, 4, 5],
              [1, 1, 1, 1, 1],
              [1, 1, 1, 1, 1]])

y = np.array([[[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]]])
print(x.shape)
print(y.shape)
print(x)
print('----------------------')
print(y)
print('----------------------')
print(x + y)

(3, 5)
(3, 3, 5)
[[1 2 3 4 5]
 [1 1 1 1 1]
 [1 1 1 1 1]]
----------------------
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]
----------------------
[[[3 4 5 6 7]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 4 5 6 7]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 4 5 6 7]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [ ]:
x = np.array([1, 2, 3, 4, 5])

y = np.array([[[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]]])
print(x.shape)
print(y.shape)
print(x)
print('----------------------')
print(y)
print('----------------------')
print(x + y)

(5,)
(3, 3, 5)
[1 2 3 4 5]
----------------------
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]
----------------------
[[[3 4 5 6 7]
  [3 4 5 6 7]
  [3 4 5 6 7]]

 [[3 4 5 6 7]
  [3 4 5 6 7]
  [3 4 5 6 7]]

 [[3 4 5 6 7]
  [3 4 5 6 7]
  [3 4 5 6 7]]]


In [ ]:
x = np.array([1])

y = np.array([[[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]],
              [[2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2],
               [2, 2, 2, 2, 2]]])
print(x.shape)
print(y.shape)
print(x)
print('----------------------')
print(y)
print('----------------------')
print(x + y)

(1,)
(3, 3, 5)
[1]
----------------------
[[[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]]
----------------------
[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


# Tensor dot
- Dot operation(tensor product) Contrary to element-wise operations, it combines entries in the input tensors.
- Dot product between two vectors is a scalar and that only vectors with the same number of elements are compatible for a dot product.

In [ ]:
def vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [ ]:
a = np.array([2, 2, 2])
b = np.array([3, 3, 3])

print(a)
print('----------------------')
print(b)
print('----------------------')
print(vector_dot(a, b))
print('----------------------')
print(np.dot(a, b))

[2 2 2]
----------------------
[3 3 3]
----------------------
18
----------------------
18


- Dot product between a matrix x and a vector y, which returns a vector where the coefficients are the dot products between y and the rows of x

In [ ]:
def matrix_vector_dot_1(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z    

- The relationship between a matrix-vector product and a vector product

In [ ]:
def matrix_vector_dot_2(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = vector_dot(x[i, :], y)
    return z

In [ ]:
a = np.array([[2, 2, 2],[3, 3, 3]])
b = np.array([4, 4, 4])
print(matrix_vector_dot_1(a, b))
print(matrix_vector_dot_2(a, b))
print(np.dot(a, b))

[24. 36.]
[24. 36.]
[24 36]


- When one of the two tensors has an ndim greater than 1, dot is no longer symmetric, dot(x, y) isn’t the same as dot(y, x).
- Dot product of two matrices x and y (dot(x, y)) if and only if x.shape[1] == y.shape[0].
- The result is a matrix with shape (x.shape[0], y.shape[1]), where the coefficients are the vector products between the rows of x and the columns of y.

In [ ]:
def matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[1], y.shape[0]))
    for i in range (x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = vector_dot(row_x, column_y)
    return z            

In [ ]:
a = np.array([[2, 2, 2],[3, 3, 3]])
b = np.array([[4, 4, 4],[5, 5, 5],[6, 6, 6]])
print(a.shape)
print(b.shape)
print(matrix_dot(a, b))
print(np.dot(a, b))

(2, 3)
(3, 3)
[[30. 30. 30.]
 [45. 45. 45.]
 [ 0.  0.  0.]]
[[30 30 30]
 [45 45 45]]


# Tensor reshaping
- Reshaping a tensor means rearranging its rows and columns to match a target shape.
- the reshaped tensor has the same total number of coefficients as the initial tensor.
- Transposing a matrix means exchanging its rows and its columns, x[i, :] becomes x[:, i]:

In [ ]:
x = np.array([[0, 1],
              [2, 3],
              [4, 5]])
print(x)
print('----------------------')
print(x.shape)
print('----------------------')
x = x.reshape(6, 1)
print(x)
print('----------------------')
print(x.shape)
print('----------------------')
x = x.reshape(1, 6)
print(x)
print('----------------------')
print(x.shape)

[[0 1]
 [2 3]
 [4 5]]
----------------------
(3, 2)
----------------------
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
----------------------
(6, 1)
----------------------
[[0 1 2 3 4 5]]
----------------------
(1, 6)
